main: org.planetfactions.envoy.Main
name: Envoy
version: '1.0.1'
description: A Envoy Plugin
softdepend: [Factions]

permissions:
   envoy.*:
      default: op
      children:
         envoy.create: true
         envoy.help: true
         envoy.debug: true
         envoy.end: true
   envoy.help:
       default: op    
   envoy.end:
       default: op        
   envoy.debug:
       default: op    
   envoy.create:
       default: op

commands:
  envoy:
   description: Shows plugin help with regular envoy command
  envoyauto:
   description: Shows plugin help with auto envoy command
     
